# Generated by Django 4.2.11 on 2024-05-30 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asistencias', '0002_alter_asistencia_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_asistencias', to=settings.AUTH_USER_MODEL),
        ),
    ]
