# Generated by Django 4.2.11 on 2024-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='materias_logo'),
        ),
    ]
